#Config File example
save_dir: workspace/efficientdet
model:
  detector:
    name: GFL
    backbone:

      name: EfficientNet
      arch: efficientnet-b2
      out_levels: [3, 4, 5]
      norm_eval: False

    neck:
      name: BiFPN
      in_channels: [48, 120, 352] #如果是b3可以采用配置 [48, 136, 384],
      out_channels: 112
      num_outs: 3
      start_level: 0
      end_level: -1
      stack: 3
    head:
      name: QuarkDetHead
      num_classes: 5 # 80
      input_channel: 112
      feat_channels: 112
      stacked_convs: 2
      share_cls_reg: True #True
      octave_base_scale: 5
      scales_per_octave: 1
      strides: [8, 16, 32]
      reg_max: 7 #16 #7
      norm_cfg:
        type: BN
      loss:
        loss_qfl:
          name: QualityFocalLoss
          use_sigmoid: True
          beta: 2.0
          loss_weight: 1.0
        loss_dfl:
          name: DistributionFocalLoss
          loss_weight: 0.25
        loss_bbox:
          name: GIoULoss
          loss_weight: 2.0
data:
  train:
    name: toss
    img_path: dataset/toss/catdog_train
    ann_path: dataset/toss/annotations/traincat.json
    input_size: [320,320] #[w,h]
    keep_ratio: True
    pipeline:
      normalize: [[103.53, 116.28, 123.675], [57.375, 57.12, 58.395]]
  val:
    name: toss
    img_path: dataset/toss/catdog_test
    ann_path: dataset/toss/annotations/testcat.json
    input_size: [320,320] #[w,h]
    keep_ratio: True
    pipeline:
      normalize: [[103.53, 116.28, 123.675], [57.375, 57.12, 58.395]]
device:
  gpu_ids: [0]
  workers_per_gpu: 8
  batchsize_per_gpu: 1 # 80 #40 #160 santiago test
schedule:
  resume: False
  load_model: ./workspace/efficientdet/model_last.pth

  optimizer:
    name: SGD
    lr: 0.14
    momentum: 0.9
    weight_decay: 0.0001
  warmup:
    name: linear
    steps: 1  #santiago test
    ratio: 0.1
  total_epochs: 90 

  lr_schedule:
    name: ReduceLROnPlateau
    mode: min
    factor: 0.1
    patience: 2 #15
    verbose: True
    threshold: 0.00001
    threshold_mode: rel
    cooldown: 0
    min_lr: 0
    eps: 0.000000001 #1e-08
  # 이 interval마다 한번씩 validation을 진행함
  val_intervals: 10
evaluator:
  name: CocoDetectionEvaluator
  save_key: mAP

log:
  interval: 10 #10
# 이 interval마다 한번씩 log기록 진행함
class_names: ["cat", "dog"]

#   {
# 	'img': tensor([
# 		[
# 			[
# 				[-2.5667, -2.5667, -2.5667, ..., -2.5667, -2.5667, -2.5667],
# 				[-2.5667, -2.5667, -2.5667, ..., -2.5667, -2.5667, -2.5667],
# 				[-2.5667, -2.5667, -2.5667, ..., -2.5667, -2.5667, -2.5667],
# 				..., [-2.5667, -2.5667, -2.5667, ..., -2.5667, -2.5667, -2.5667],
# 				[-2.5667, -2.5667, -2.5667, ..., -2.5667, -2.5667, -2.5667],
# 				[-2.5667, -2.5667, -2.5667, ..., -2.5667, -2.5667, -2.5667]
# 			],

# 			[
# 				[-2.8013, -2.8013, -2.8013, ..., -2.8013, -2.8013, -2.8013],
# 				[-2.8013, -2.8013, -2.8013, ..., -2.8013, -2.8013, -2.8013],
# 				[-2.8013, -2.8013, -2.8013, ..., -2.8013, -2.8013, -2.8013],
# 				..., [-2.8013, -2.8013, -2.8013, ..., -2.8013, -2.8013, -2.8013],
# 				[-2.8013, -2.8013, -2.8013, ..., -2.8013, -2.8013, -2.8013],
# 				[-2.8013, -2.8013, -2.8013, ..., -2.8013, -2.8013, -2.8013]
# 			],

# 			[
# 				[-2.8668, -2.8668, -2.8668, ..., -2.8668, -2.8668, -2.8668],
# 				[-2.8668, -2.8668, -2.8668, ..., -2.8668, -2.8668, -2.8668],
# 				[-2.8668, -2.8668, -2.8668, ..., -2.8668, -2.8668, -2.8668],
# 				..., [-2.8668, -2.8668, -2.8668, ..., -2.8668, -2.8668, -2.8668],
# 				[-2.8668, -2.8668, -2.8668, ..., -2.8668, -2.8668, -2.8668],
# 				[-2.8668, -2.8668, -2.8668, ..., -2.8668, -2.8668, -2.8668]
# 			]
# 		]
# 	]),
# 	'img_info': {
# 		'license': tensor([2]),
# 		'file_name': ['000000007616.jpg'],
# 		'coco_url': ['http://images.cocodataset.org/train2017/000000007616.jpg'],
# 		'height': tensor([375]),
# 		'width': tensor([500]),
# 		'date_captured': ['2013-11-16 19:22:23'],
# 		'flickr_url': ['http://farm1.staticflickr.com/3/6939216_ea2aca1399_z.jpg'],
# 		'id': tensor([7616])
# 	},
# 	'gt_bboxes': [array([
# 			[193.312, 153.37599, 216.5952, 175.8784],
# 			[110.0224, 135.4624, 208.1792, 215.2832],
# 			[160.1216, 85.7984, 168.64641, 110.976],
# 			[204.7232, 93.6704, 212.2048, 108.3904],
# 			[85.414406, 148.8192, 111.8976, 167.5584],
# 			[236.0832, 155.96161, 267.5264, 166.3424],
# 			[1.0816001, 231.6224, 320., 277.568],
# 			[85.4656, 148.3776, 112.22401, 168.096],
# 			[40.7232, 109.024, 44.607998, 121.5552]
# 		],
# 		dtype = float32)],
# 	'gt_labels': [array([2, 7, 9, 9, 2, 2, 2, 7, 9])],
# 	'warp_matrix': [array([
# 		[0.64, 0., 0.],
# 		[0., 0.64, 40.],
# 		[0., 0., 1.]
# 	])]
# }
